System.config({
  baseURL: ".",
  defaultJSExtensions: true,
  transpiler: "typescript",
  paths: {
    "npm:*": "jspm_packages/npm/*",
    "github:*": "jspm_packages/github/*"
  },
  bundles: {
    "dist/demo.js": [
      "framework/components/ui-datagrid.html!github:systemjs/plugin-text@0.0.4.js",
      "framework/components/ui-datagrid.js",
      "framework/components/ui-dialog.js",
      "framework/components/ui-form.html!github:systemjs/plugin-text@0.0.4.js",
      "framework/components/ui-form.js",
      "framework/components/ui-header.html!github:systemjs/plugin-text@0.0.4.js",
      "framework/components/ui-login.html!github:systemjs/plugin-text@0.0.4.js",
      "framework/components/ui-login.js",
      "framework/components/ui-menu.html!github:systemjs/plugin-text@0.0.4.js",
      "framework/components/ui-menu.js",
      "framework/components/ui-pager.html!github:systemjs/plugin-text@0.0.4.js",
      "framework/components/ui-panel.html!github:systemjs/plugin-text@0.0.4.js",
      "framework/components/ui-panel.js",
      "framework/components/ui-ribbon.html!github:systemjs/plugin-text@0.0.4.js",
      "framework/components/ui-ribbon.js",
      "framework/components/ui-tab-panel.html!github:systemjs/plugin-text@0.0.4.js",
      "framework/components/ui-tab-panel.js",
      "framework/components/ui-tree-node.html!github:systemjs/plugin-text@0.0.4.js",
      "framework/components/ui-tree.html!github:systemjs/plugin-text@0.0.4.js",
      "framework/components/ui-tree.js",
      "framework/core/ui-app-menu.html!github:systemjs/plugin-text@0.0.4.js",
      "framework/core/ui-grid.js",
      "framework/core/ui-page.html!github:systemjs/plugin-text@0.0.4.js",
      "framework/core/ui-page.js",
      "framework/core/ui-viewport.html!github:systemjs/plugin-text@0.0.4.js",
      "framework/core/ui-viewport.js",
      "framework/data/countries.js",
      "framework/data/currencies.js",
      "framework/index.js",
      "framework/inputs/ui-button.html!github:systemjs/plugin-text@0.0.4.js",
      "framework/inputs/ui-button.js",
      "framework/inputs/ui-combo.html!github:systemjs/plugin-text@0.0.4.js",
      "framework/inputs/ui-combo.js",
      "framework/inputs/ui-date-view.html!github:systemjs/plugin-text@0.0.4.js",
      "framework/inputs/ui-date-view.js",
      "framework/inputs/ui-date.html!github:systemjs/plugin-text@0.0.4.js",
      "framework/inputs/ui-date.js",
      "framework/inputs/ui-input-dual.js",
      "framework/inputs/ui-input-group.js",
      "framework/inputs/ui-input.html!github:systemjs/plugin-text@0.0.4.js",
      "framework/inputs/ui-input.js",
      "framework/inputs/ui-json-editor.js",
      "framework/inputs/ui-json-part.html!github:systemjs/plugin-text@0.0.4.js",
      "framework/inputs/ui-language.html!github:systemjs/plugin-text@0.0.4.js",
      "framework/inputs/ui-language.js",
      "framework/inputs/ui-list-group.html!github:systemjs/plugin-text@0.0.4.js",
      "framework/inputs/ui-list-item.html!github:systemjs/plugin-text@0.0.4.js",
      "framework/inputs/ui-markdown.html!github:systemjs/plugin-text@0.0.4.js",
      "framework/inputs/ui-markdown.js",
      "framework/inputs/ui-option-group.html!github:systemjs/plugin-text@0.0.4.js",
      "framework/inputs/ui-option.html!github:systemjs/plugin-text@0.0.4.js",
      "framework/inputs/ui-option.js",
      "framework/inputs/ui-phone.js",
      "framework/inputs/ui-switch.html!github:systemjs/plugin-text@0.0.4.js",
      "framework/inputs/ui-switch.js",
      "framework/inputs/ui-tags.html!github:systemjs/plugin-text@0.0.4.js",
      "framework/inputs/ui-tags.js",
      "framework/inputs/ui-textarea.html!github:systemjs/plugin-text@0.0.4.js",
      "framework/inputs/ui-textarea.js",
      "framework/libs/marked.js",
      "framework/libs/phonelib.js",
      "framework/utils/ui-application.js",
      "framework/utils/ui-converters.js",
      "framework/utils/ui-event.js",
      "framework/utils/ui-formatters.js",
      "framework/utils/ui-http-service.js",
      "framework/utils/ui-model.js",
      "framework/utils/ui-tree-models.js",
      "framework/utils/ui-utils.js",
      "framework/utils/ui-validation.js",
      "github:github/fetch@0.11.1.js",
      "github:github/fetch@0.11.1/fetch.js",
      "github:jspm/nodelibs-buffer@0.1.0.js",
      "github:jspm/nodelibs-buffer@0.1.0/index.js",
      "github:jspm/nodelibs-process@0.1.2.js",
      "github:jspm/nodelibs-process@0.1.2/index.js",
      "main.js",
      "npm:aurelia-binding@1.0.0-beta.1.3.4.js",
      "npm:aurelia-binding@1.0.0-beta.1.3.4/aurelia-binding.js",
      "npm:aurelia-bootstrapper@1.0.0-beta.1.2.0.js",
      "npm:aurelia-bootstrapper@1.0.0-beta.1.2.0/aurelia-bootstrapper.js",
      "npm:aurelia-dependency-injection@1.0.0-beta.1.2.2.js",
      "npm:aurelia-dependency-injection@1.0.0-beta.1.2.2/aurelia-dependency-injection.js",
      "npm:aurelia-event-aggregator@1.0.0-beta.1.2.0.js",
      "npm:aurelia-event-aggregator@1.0.0-beta.1.2.0/aurelia-event-aggregator.js",
      "npm:aurelia-fetch-client@1.0.0-beta.1.2.3.js",
      "npm:aurelia-fetch-client@1.0.0-beta.1.2.3/aurelia-fetch-client.js",
      "npm:aurelia-framework@1.0.0-beta.1.2.2.js",
      "npm:aurelia-framework@1.0.0-beta.1.2.2/aurelia-framework.js",
      "npm:aurelia-history-browser@1.0.0-beta.1.2.0.js",
      "npm:aurelia-history-browser@1.0.0-beta.1.2.0/aurelia-history-browser.js",
      "npm:aurelia-history@1.0.0-beta.1.2.0.js",
      "npm:aurelia-history@1.0.0-beta.1.2.0/aurelia-history.js",
      "npm:aurelia-loader-default@1.0.0-beta.1.2.1.js",
      "npm:aurelia-loader-default@1.0.0-beta.1.2.1/aurelia-loader-default.js",
      "npm:aurelia-loader@1.0.0-beta.1.2.0.js",
      "npm:aurelia-loader@1.0.0-beta.1.2.0/aurelia-loader.js",
      "npm:aurelia-logging-console@1.0.0-beta.1.2.0.js",
      "npm:aurelia-logging-console@1.0.0-beta.1.2.0/aurelia-logging-console.js",
      "npm:aurelia-logging@1.0.0-beta.1.2.0.js",
      "npm:aurelia-logging@1.0.0-beta.1.2.0/aurelia-logging.js",
      "npm:aurelia-metadata@1.0.0-beta.1.2.0.js",
      "npm:aurelia-metadata@1.0.0-beta.1.2.0/aurelia-metadata.js",
      "npm:aurelia-pal-browser@1.0.0-beta.1.2.0.js",
      "npm:aurelia-pal-browser@1.0.0-beta.1.2.0/aurelia-pal-browser.js",
      "npm:aurelia-pal@1.0.0-beta.1.2.1.js",
      "npm:aurelia-pal@1.0.0-beta.1.2.1/aurelia-pal.js",
      "npm:aurelia-path@1.0.0-beta.1.2.1.js",
      "npm:aurelia-path@1.0.0-beta.1.2.1/aurelia-path.js",
      "npm:aurelia-polyfills@1.0.0-beta.1.1.3.js",
      "npm:aurelia-polyfills@1.0.0-beta.1.1.3/aurelia-polyfills.js",
      "npm:aurelia-route-recognizer@1.0.0-beta.1.2.0.js",
      "npm:aurelia-route-recognizer@1.0.0-beta.1.2.0/aurelia-route-recognizer.js",
      "npm:aurelia-router@1.0.0-beta.1.2.1.js",
      "npm:aurelia-router@1.0.0-beta.1.2.1/aurelia-router.js",
      "npm:aurelia-task-queue@1.0.0-beta.1.2.0.js",
      "npm:aurelia-task-queue@1.0.0-beta.1.2.0/aurelia-task-queue.js",
      "npm:aurelia-templating-binding@1.0.0-beta.1.2.3.js",
      "npm:aurelia-templating-binding@1.0.0-beta.1.2.3/aurelia-templating-binding.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.4.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.4/abstract-repeater.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.4/analyze-view-factory.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.4/array-repeat-strategy.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.4/aurelia-templating-resources.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.4/binding-mode-behaviors.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.4/binding-signaler.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.4/compile-spy.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.4/compose.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.4/css-resource.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.4/debounce-binding-behavior.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.4/dynamic-element.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.4/focus.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.4/hide.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.4/html-resource-plugin.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.4/html-sanitizer.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.4/if.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.4/map-repeat-strategy.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.4/null-repeat-strategy.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.4/number-repeat-strategy.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.4/repeat-strategy-locator.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.4/repeat-utilities.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.4/repeat.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.4/replaceable.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.4/sanitize-html.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.4/set-repeat-strategy.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.4/show.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.4/signal-binding-behavior.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.4/throttle-binding-behavior.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.4/update-trigger-binding-behavior.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.4/view-spy.js",
      "npm:aurelia-templating-resources@1.0.0-beta.1.2.4/with.js",
      "npm:aurelia-templating-router@1.0.0-beta.1.2.0.js",
      "npm:aurelia-templating-router@1.0.0-beta.1.2.0/aurelia-templating-router.js",
      "npm:aurelia-templating-router@1.0.0-beta.1.2.0/route-href.js",
      "npm:aurelia-templating-router@1.0.0-beta.1.2.0/route-loader.js",
      "npm:aurelia-templating-router@1.0.0-beta.1.2.0/router-view.js",
      "npm:aurelia-templating@1.0.0-beta.1.2.5.js",
      "npm:aurelia-templating@1.0.0-beta.1.2.5/aurelia-templating.js",
      "npm:aurelia-validation@0.6.8.js",
      "npm:aurelia-validation@0.6.8/debouncer.js",
      "npm:aurelia-validation@0.6.8/decorators.js",
      "npm:aurelia-validation@0.6.8/index.js",
      "npm:aurelia-validation@0.6.8/path-observer.js",
      "npm:aurelia-validation@0.6.8/resources/bg-BG.js",
      "npm:aurelia-validation@0.6.8/resources/ca-ES.js",
      "npm:aurelia-validation@0.6.8/resources/da-DK.js",
      "npm:aurelia-validation@0.6.8/resources/de-DE.js",
      "npm:aurelia-validation@0.6.8/resources/en-US.js",
      "npm:aurelia-validation@0.6.8/resources/es-MX.js",
      "npm:aurelia-validation@0.6.8/resources/fr-FR.js",
      "npm:aurelia-validation@0.6.8/resources/ja-JP.js",
      "npm:aurelia-validation@0.6.8/resources/nb-NO.js",
      "npm:aurelia-validation@0.6.8/resources/nl-BE.js",
      "npm:aurelia-validation@0.6.8/resources/nl-NL.js",
      "npm:aurelia-validation@0.6.8/resources/nn-NO.js",
      "npm:aurelia-validation@0.6.8/resources/pt-BR.js",
      "npm:aurelia-validation@0.6.8/resources/sv-SE.js",
      "npm:aurelia-validation@0.6.8/resources/tr-TR.js",
      "npm:aurelia-validation@0.6.8/resources/zh-CN.js",
      "npm:aurelia-validation@0.6.8/strategies/twbootstrap-view-strategy.js",
      "npm:aurelia-validation@0.6.8/utilities.js",
      "npm:aurelia-validation@0.6.8/validate-custom-attribute.js",
      "npm:aurelia-validation@0.6.8/validation-config.js",
      "npm:aurelia-validation@0.6.8/validation-group-builder.js",
      "npm:aurelia-validation@0.6.8/validation-group.js",
      "npm:aurelia-validation@0.6.8/validation-locale.js",
      "npm:aurelia-validation@0.6.8/validation-property.js",
      "npm:aurelia-validation@0.6.8/validation-result.js",
      "npm:aurelia-validation@0.6.8/validation-rules-collection.js",
      "npm:aurelia-validation@0.6.8/validation-rules.js",
      "npm:aurelia-validation@0.6.8/validation-view-strategy.js",
      "npm:aurelia-validation@0.6.8/validation.js",
      "npm:base64-js@0.0.8.js",
      "npm:base64-js@0.0.8/lib/b64.js",
      "npm:buffer@3.6.0.js",
      "npm:buffer@3.6.0/index.js",
      "npm:ieee754@1.1.6.js",
      "npm:ieee754@1.1.6/index.js",
      "npm:isarray@1.0.0.js",
      "npm:isarray@1.0.0/index.js",
      "npm:lodash@4.12.0.js",
      "npm:lodash@4.12.0/lodash.js",
      "npm:moment@2.13.0.js",
      "npm:moment@2.13.0/moment.js",
      "npm:numeral@1.5.3.js",
      "npm:numeral@1.5.3/numeral.js",
      "npm:process@0.11.3.js",
      "npm:process@0.11.3/browser.js",
      "src/app.html!github:systemjs/plugin-text@0.0.4.js",
      "src/app.js",
      "src/components/readme.js",
      "src/components/view.html!github:systemjs/plugin-text@0.0.4.js",
      "src/components/view.js",
      "src/core/readme.js",
      "src/core/view.html!github:systemjs/plugin-text@0.0.4.js",
      "src/core/view.js",
      "src/highlight.js",
      "src/home/colors.html!github:systemjs/plugin-text@0.0.4.js",
      "src/home/colors.js",
      "src/home/my-dialog.html!github:systemjs/plugin-text@0.0.4.js",
      "src/home/my-dialog.js",
      "src/home/readme.js",
      "src/home/todo.js",
      "src/home/view.html!github:systemjs/plugin-text@0.0.4.js",
      "src/home/view.js",
      "src/inputs/readme.js",
      "src/inputs/view.html!github:systemjs/plugin-text@0.0.4.js",
      "src/inputs/view.js",
      "src/login/view.html!github:systemjs/plugin-text@0.0.4.js",
      "src/login/view.js",
      "src/utils/readme.js",
      "src/utils/view.html!github:systemjs/plugin-text@0.0.4.js",
      "src/utils/view.js"
    ]
  },

  map: {
    "aurelia-bootstrapper": "npm:aurelia-bootstrapper@1.0.0-beta.1.2.0",
    "aurelia-event-aggregator": "npm:aurelia-event-aggregator@1.0.0-beta.1.2.0",
    "aurelia-fetch-client": "npm:aurelia-fetch-client@1.0.0-beta.1.2.3",
    "aurelia-framework": "npm:aurelia-framework@1.0.0-beta.1.2.2",
    "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.2.0",
    "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.2.0",
    "aurelia-router": "npm:aurelia-router@1.0.0-beta.1.2.1",
    "aurelia-templating-resources": "npm:aurelia-templating-resources@1.0.0-beta.1.2.4",
    "aurelia-validation": "npm:aurelia-validation@0.6.8",
    "fetch": "github:github/fetch@0.11.1",
    "lodash": "npm:lodash@4.12.0",
    "moment": "npm:moment@2.13.0",
    "numeral": "npm:numeral@1.5.3",
    "text": "github:systemjs/plugin-text@0.0.4",
    "typescript": "npm:typescript@1.8.10",
    "github:jspm/nodelibs-assert@0.1.0": {
      "assert": "npm:assert@1.3.0"
    },
    "github:jspm/nodelibs-buffer@0.1.0": {
      "buffer": "npm:buffer@3.6.0"
    },
    "github:jspm/nodelibs-os@0.1.0": {
      "os-browserify": "npm:os-browserify@0.1.2"
    },
    "github:jspm/nodelibs-process@0.1.2": {
      "process": "npm:process@0.11.3"
    },
    "github:jspm/nodelibs-util@0.1.0": {
      "util": "npm:util@0.10.3"
    },
    "npm:assert@1.3.0": {
      "util": "npm:util@0.10.3"
    },
    "npm:aurelia-binding@1.0.0-beta.1.3.4": {
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.2.0",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.2.0",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.1",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.0.0-beta.1.2.0"
    },
    "npm:aurelia-bootstrapper@1.0.0-beta.1.2.0": {
      "aurelia-event-aggregator": "npm:aurelia-event-aggregator@1.0.0-beta.1.2.0",
      "aurelia-framework": "npm:aurelia-framework@1.0.0-beta.1.2.2",
      "aurelia-history": "npm:aurelia-history@1.0.0-beta.1.2.0",
      "aurelia-history-browser": "npm:aurelia-history-browser@1.0.0-beta.1.2.0",
      "aurelia-loader-default": "npm:aurelia-loader-default@1.0.0-beta.1.2.1",
      "aurelia-logging-console": "npm:aurelia-logging-console@1.0.0-beta.1.2.0",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.1",
      "aurelia-pal-browser": "npm:aurelia-pal-browser@1.0.0-beta.1.2.0",
      "aurelia-polyfills": "npm:aurelia-polyfills@1.0.0-beta.1.1.3",
      "aurelia-router": "npm:aurelia-router@1.0.0-beta.1.2.1",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.2.5",
      "aurelia-templating-binding": "npm:aurelia-templating-binding@1.0.0-beta.1.2.3",
      "aurelia-templating-resources": "npm:aurelia-templating-resources@1.0.0-beta.1.2.4",
      "aurelia-templating-router": "npm:aurelia-templating-router@1.0.0-beta.1.2.0"
    },
    "npm:aurelia-dependency-injection@1.0.0-beta.1.2.2": {
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.2.0",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.2.0",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.1"
    },
    "npm:aurelia-event-aggregator@1.0.0-beta.1.2.0": {
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.2.0"
    },
    "npm:aurelia-framework@1.0.0-beta.1.2.2": {
      "aurelia-binding": "npm:aurelia-binding@1.0.0-beta.1.3.4",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1.2.2",
      "aurelia-loader": "npm:aurelia-loader@1.0.0-beta.1.2.0",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.2.0",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.2.0",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.1",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1.2.1",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.0.0-beta.1.2.0",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.2.5"
    },
    "npm:aurelia-history-browser@1.0.0-beta.1.2.0": {
      "aurelia-history": "npm:aurelia-history@1.0.0-beta.1.2.0",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.1"
    },
    "npm:aurelia-loader-default@1.0.0-beta.1.2.1": {
      "aurelia-loader": "npm:aurelia-loader@1.0.0-beta.1.2.0",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.2.0",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.1"
    },
    "npm:aurelia-loader@1.0.0-beta.1.2.0": {
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.2.0",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1.2.1"
    },
    "npm:aurelia-logging-console@1.0.0-beta.1.2.0": {
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.2.0",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.1"
    },
    "npm:aurelia-metadata@1.0.0-beta.1.2.0": {
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.1"
    },
    "npm:aurelia-pal-browser@1.0.0-beta.1.2.0": {
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.1"
    },
    "npm:aurelia-polyfills@1.0.0-beta.1.1.3": {
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.1"
    },
    "npm:aurelia-route-recognizer@1.0.0-beta.1.2.0": {
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1.2.1"
    },
    "npm:aurelia-router@1.0.0-beta.1.2.1": {
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1.2.2",
      "aurelia-event-aggregator": "npm:aurelia-event-aggregator@1.0.0-beta.1.2.0",
      "aurelia-history": "npm:aurelia-history@1.0.0-beta.1.2.0",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.2.0",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1.2.1",
      "aurelia-route-recognizer": "npm:aurelia-route-recognizer@1.0.0-beta.1.2.0"
    },
    "npm:aurelia-task-queue@1.0.0-beta.1.2.0": {
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.1"
    },
    "npm:aurelia-templating-binding@1.0.0-beta.1.2.3": {
      "aurelia-binding": "npm:aurelia-binding@1.0.0-beta.1.3.4",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.2.0",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.2.5"
    },
    "npm:aurelia-templating-resources@1.0.0-beta.1.2.4": {
      "aurelia-binding": "npm:aurelia-binding@1.0.0-beta.1.3.4",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1.2.2",
      "aurelia-loader": "npm:aurelia-loader@1.0.0-beta.1.2.0",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.2.0",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.2.0",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.1",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1.2.1",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.0.0-beta.1.2.0",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.2.5"
    },
    "npm:aurelia-templating-router@1.0.0-beta.1.2.0": {
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1.2.2",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.2.0",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.2.0",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.1",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1.2.1",
      "aurelia-router": "npm:aurelia-router@1.0.0-beta.1.2.1",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.2.5"
    },
    "npm:aurelia-templating@1.0.0-beta.1.2.5": {
      "aurelia-binding": "npm:aurelia-binding@1.0.0-beta.1.3.4",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1.2.2",
      "aurelia-loader": "npm:aurelia-loader@1.0.0-beta.1.2.0",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.2.0",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.2.0",
      "aurelia-pal": "npm:aurelia-pal@1.0.0-beta.1.2.1",
      "aurelia-path": "npm:aurelia-path@1.0.0-beta.1.2.1",
      "aurelia-task-queue": "npm:aurelia-task-queue@1.0.0-beta.1.2.0"
    },
    "npm:aurelia-validation@0.6.8": {
      "aurelia-binding": "npm:aurelia-binding@1.0.0-beta.1.3.4",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.0.0-beta.1.2.2",
      "aurelia-loader": "npm:aurelia-loader@1.0.0-beta.1.2.0",
      "aurelia-logging": "npm:aurelia-logging@1.0.0-beta.1.2.0",
      "aurelia-metadata": "npm:aurelia-metadata@1.0.0-beta.1.2.0",
      "aurelia-templating": "npm:aurelia-templating@1.0.0-beta.1.2.5"
    },
    "npm:buffer@3.6.0": {
      "base64-js": "npm:base64-js@0.0.8",
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "ieee754": "npm:ieee754@1.1.6",
      "isarray": "npm:isarray@1.0.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:inherits@2.0.1": {
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:isarray@1.0.0": {
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:lodash@4.12.0": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:numeral@1.5.3": {
      "fs": "github:jspm/nodelibs-fs@0.1.2"
    },
    "npm:os-browserify@0.1.2": {
      "os": "github:jspm/nodelibs-os@0.1.0"
    },
    "npm:process@0.11.3": {
      "assert": "github:jspm/nodelibs-assert@0.1.0"
    },
    "npm:typescript@1.8.10": {
      "os": "github:jspm/nodelibs-os@0.1.0"
    },
    "npm:util@0.10.3": {
      "inherits": "npm:inherits@2.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    }
  }
});
