"use strict";
require('fetch');
require('lodash');
require('moment');
require('numeral');
require('./libs/marked');
require('./libs/highlight');
require('./libs/phonelib');
require('./data/countries');
require('./data/currencies');
var ui_application_1 = require("./utils/ui-application");
function configure(aurelia, configCallback) {
    aurelia.globalResources('./core/ui-viewport');
    aurelia.globalResources('./core/ui-page');
    aurelia.globalResources('./core/ui-grid');
    aurelia.globalResources('./components/ui-menu');
    aurelia.globalResources('./components/ui-form');
    aurelia.globalResources('./components/ui-ribbon');
    aurelia.globalResources('./components/ui-panel');
    aurelia.globalResources('./components/ui-login');
    aurelia.globalResources('./components/ui-tree');
    aurelia.globalResources('./components/ui-datagrid');
    aurelia.globalResources('./components/ui-tab-panel');
    aurelia.globalResources('./inputs/ui-button');
    aurelia.globalResources('./inputs/ui-switch');
    aurelia.globalResources('./inputs/ui-option');
    aurelia.globalResources('./inputs/ui-input');
    aurelia.globalResources('./inputs/ui-phone');
    aurelia.globalResources('./inputs/ui-markdown');
    aurelia.globalResources('./inputs/ui-textarea');
    aurelia.globalResources('./inputs/ui-input-dual');
    aurelia.globalResources('./inputs/ui-combo');
    aurelia.globalResources('./inputs/ui-tags');
    aurelia.globalResources('./inputs/ui-language');
    aurelia.globalResources('./inputs/ui-date');
    aurelia.globalResources('./inputs/ui-date-view');
    aurelia.globalResources('./utils/ui-converters');
    if (configCallback !== undefined && typeof configCallback === 'function') {
        configCallback(ui_application_1.UIApplication.defaults);
    }
}
exports.configure = configure;
var ui_event_1 = require("./utils/ui-event");
exports.UIEvent = ui_event_1.UIEvent;
var ui_formatters_1 = require("./utils/ui-formatters");
exports.UIFormat = ui_formatters_1.UIFormat;
var ui_application_2 = require("./utils/ui-application");
exports.UIApplication = ui_application_2.UIApplication;
exports.AuthInterceptor = ui_application_2.AuthInterceptor;
var ui_model_1 = require("./utils/ui-model");
exports.UIModel = ui_model_1.UIModel;
var ui_language_1 = require("./inputs/ui-language");
exports.UILanguage = ui_language_1.UILanguage;
var ui_dialog_1 = require("./components/ui-dialog");
exports.UIDialogService = ui_dialog_1.UIDialogService;
exports.UIDialog = ui_dialog_1.UIDialog;
var ui_tree_models_1 = require("./utils/ui-tree-models");
exports.UITreeModel = ui_tree_models_1.UITreeModel;
exports.UITreeOptions = ui_tree_models_1.UITreeOptions;
var ui_http_service_1 = require("./utils/ui-http-service");
exports.UIHttpService = ui_http_service_1.UIHttpService;
var ui_validation_1 = require("./utils/ui-validation");
exports.UIValidationStrategy = ui_validation_1.UIValidationStrategy;
var ui_utils_1 = require("./utils/ui-utils");
exports.UIUtils = ui_utils_1.UIUtils;
exports._ = ui_utils_1._;
exports.moment = ui_utils_1.moment;
exports.numeral = ui_utils_1.numeral;
